import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ann's Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row flex-nowrap bg-sky-300 w-full gap-2 justify-end">
          <Link className="border border-1 border-black p-3 w-fit text-center" href="/">Home</Link>
          <Link className="border border-1 border-black p-3 w-fit text-center" href="/contact">Contact</Link>
          <Link className="border border-1 border-black p-3 w-fit text-center" href="/about">About Me</Link>
          <Link className="border border-1 border-black p-3 w-fit text-center" href="/games">Games I like</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
